### ISSUE TITLE
Snapshot Creation

### ISSUE THREAD

**Issue by hellracer** [olivierlambert/Xen-Orchestra#1]
Creating a VM snapshot is too silent and no confirmation at all I don't know if this has something to do with the way the VM has been named.

e.g

192.168.195.17 - Xen Orchestra (Console) when I take the snapshot it didn't show on the list. but logging to XenCenter it was ok.

XenOrchesta v3.4

Browser Affected : Google Chrome / Firefox

**Comment by olivierlambert** [comment]
Hi,

Can you be more specific? When you create a snapshot in the Web GUI, the created snapshot doesn't show up?

The current process is documented here: https://github.com/vatesfr/xo-web/blob/next-release/doc/vm/README.md#snapshots-management

Please check this doc and tell me when it goes wrong.

Thanks :)
