### ISSUE TITLE
Can´t upgrade throug Web GUI

### ISSUE THREAD

**Issue by Notaduck** [olivierlambert/Xen-Orchestra#2]
i just imported the XOA and i am getting this error when i try to upgrade

ENOENT, lstat '/usr/local/lib/node_modules/xoa-updater'

**Comment by olivierlambert** [comment]
Hi!

You are not on the right repo for submitting bugs (cf the big warning in the README).

Anyway, your problem looks like a DNS resolution problem. Check your `/etc/resolv.conf` and use a correct resolver reachable in your network (`8.8.8.8` should work for example)
